FROM         centos:latest
MAINTAINER    dwy

#把java与tomcat添加到容器中
ADD jdk-8u181-linux-x64.tar.gz /usr/local/
ADD apache-tomcat-8.5.34.tar.gz /usr/local/
ADD hello.html /usr/local/apache-tomcat-8.5.34/webapps/ROOT/

#配置java与tomcat环境变量
ENV JAVA_HOME /usr/local/jdk1.8.0_181
ENV JRE_HOME /usr/local/jdk1.8.0_181/jre
ENV JAVA_OPTS "-server -Xmx2048m -Dfile.encoding=UTF8 -Duser.timezone=GMT+08"
ENV CLASSPATH $JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
ENV CATALINA_HOME /usr/local/apache-tomcat-8.5.34
ENV CATALINA_BASE /usr/local/apache-tomcat-8.5.34
ENV PATH $PATH:$JAVA_HOME/bin:$CATALINA_HOME/lib:$CATALINA_HOME/bin
ENV JAVA_VERSION 8u181
ENV TOMCAT_MAJOR 8
ENV TOMCAT_VERSION 8.5.34
ENV LANG C.UTF-8

# CentOS
#RUN echo "Asia/shanghai" > /etc/timezone

# Ubuntu
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

CMD ["catalina.sh","run"]

#容器运行时监听的端口
EXPOSE  8080