FROM registry.cn-shenzhen.aliyuncs.com/ljdp/nginx

MAINTAINER dwy

ADD ABTestingGateway.tar.gz /software/nginx/
ADD start.sh /
RUN chmod +x /start.sh

#COPY /software/nginx/ABTestingGateway/utils/conf/nginx.conf /software/nginx/
#COPY /software/nginx/ABTestingGateway/utils/conf/default.conf /software/nginx/conf.d
#COPY /software/nginx/ABTestingGateway/utils/conf/stable.conf /software/nginx/conf.d
#COPY /software/nginx/ABTestingGateway/utils/conf/upstream.conf /software/nginx/conf.d
#COPY /software/nginx/ABTestingGateway/utils/conf/vhost.conf /software/nginx/conf.d
#COPY /software/nginx/ABTestingGateway/utils/conf/beta1.conf /software/nginx/conf.d
#COPY /software/nginx/ABTestingGateway/utils/conf/beta2.conf /software/nginx/conf.d

CMD ["source","/start.sh"]
#ENTRYPOINT /start.sh