FROM         jenkins/jenkins:lts
MAINTAINER    dwy

COPY	get-pip.py /tmp/
# if we want to install via apt
USER root
RUN   python /tmp/get-pip.py \
	&& pip install requests

RUN apt-get update && apt-get install -y apt-transport-https \
	&& apt-get install -y  kubectl 
	
# drop back to the regular jenkins user - good practice
USER jenkins
