FROM         jenkins/jenkins:lts
MAINTAINER    dwy

COPY	get-pip.py /tmp/
# if we want to install via apt
USER root
RUN   python /tmp/get-pip.py \
	&& pip install requests

RUN apt-get update && apt-get install -y apt-transport-https \
	&& curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl \
	&&  chmod +x ./kubectl \
	&&  mv ./kubectl /usr/local/bin/kubectl \
	&& mkdir /root/.kube \
    && touch /root/.kube/config \\
	&& apt-get install vi
	
# drop back to the regular jenkins user - good practice
#USER jenkins
