FROM centos

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN yum -y update && yum -y install epel-release && yum -y install redis
EXPOSE 6379
RUN yum clean all

RUN apt-get update \
    && apt-get install -y git  \
    && cd   \tmp \
    && git clone https://github.com/kevindwei/ABTestingGateway.git

#copy conf 
RUN  rm -rf /etc/redis.conf \
   && cp /tmp/ABTestingGateway/utils/conf/redis.conf  /etc/

#修改绑定IP地址
#RUN sed -i -e 's@# bind 127.0.0.1@bind 0.0.0.0@g' /etc/redis.conf
#关闭保护模式
#RUN sed -i -e 's@protected-mode yes@protected-mode no@g' /etc/redis.conf


#启动
#ENTRYPOINT [ "/usr/bin/redis-server","/tmp/ABTestingGateway/utils/conf/redis.conf"]