FROM registry.cn-shenzhen.aliyuncs.com/spider2/nginx-lua:latest

MAINTAINER dwy


RUN apt-get update \
    && apt-get install -y git  \
    && cd /   \
    && git clone https://github.com/kevindwei/ABTestingGateway.git
 
RUN chmod +x /ABTestingGateway/util/start.sh

#ENTRYPOINT ["/start.sh"]