FROM         centos:latest
MAINTAINER    dwy

#把java添加到容器中
ADD jdk-8u181-linux-x64.tar.gz /usr/local/


#配置java与tomcat环境变量
ENV JAVA_HOME /usr/local/jdk1.8.0_181
ENV CLASSPATH $JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
ENV PATH $PATH:$JAVA_HOME/bin