# 设置继承自ubuntu官方镜像
FROM ubuntu:latest 

MAINTAINER dwy

RUN apt-get update && apt-get install -y --no-install-recommends \
		ca-certificates \
		wget \
    curl \
    vim \
		&& rm -rf /var/lib/apt/lists/*


RUN echo "Asia/Shanghai" > /etc/timezone \
	&& ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

# 添加User和Group
RUN groupadd -r nginx \
    && useradd -r -g nginx nginx

# 设置 NGINX 的环境变量，若读者有其他的环境变量需要设置，也可以在这里添加。
ENV NGX_OPENRESTY_HOME /software/nginx 


# 安装依赖
RUN apt-get update \
    && apt-get -y install libreadline-dev libncurses5-dev libpcre3-dev libssl-dev perl   \
		&& rm -rf /var/lib/apt/lists/*    
        

ENV ngx_openresty_VERSION 1.9.7.1



#该模块用于清理nginx缓存
ADD ngx_cache_purge-2.3.tar.gz /software/temp
#该模块用于ustream健康检查
ADD nginx_upstream_check_module-0.3.0.tar.gz /software/temp

RUN mkdir -p /software/temp



RUN wget https://openresty.org/download/ngx_openresty-${ngx_openresty_VERSION}.tar.gz \
    && tar -zxvf ngx_openresty-${ngx_openresty_VERSION}.tar.gz -C /software/temp


	
#安装LuaJIT  
RUN cd /software/temp/ngx_openresty-${ngx_openresty_VERSION}/bundle/LuaJIT-2.1-20151219/ \
    make clean && make && make install \
    && ln -sf luajit-2.1.0-alpha /usr/local/bin/luajit 
    
#安装ngx_openresty
RUN cd  /software/temp/ngx_openresty-${ngx_openresty_VERSION}   \
    && ./configure --prefix=${NGX_OPENRESTY_HOME}  \
                   --with-http_realip_module  \
                   --with-pcre    \
                   --with-luajit  \
                   --add-module=./bundle/ngx_cache_purge-2.3/   \
                   --add-module=./bundle/nginx_upstream_check_module-0.3.0/  \
                   -j2  \
    && make  \
	&& make install


#EXPOSE 80 


